In [16]:
import os
import requests
import pandas as pd
from pprint import pprint

# Foursquare

In [ ]:
Send a request to Foursquare with a small radius (1000m) for all the bike stations in your city of choice.

In [17]:
FOURSQUARE_API_KEY = os.getenv('FOURSQUARE_API_KEY')

In [18]:
FOURSQUARE_API_KEY = os.getenv('FOURSQUARE_API_KEY')

df_bikes_paris = pd.read_csv('bikes_paris_csv.csv')

latitude = df_bikes_paris.loc[0,'latitude']
longitude = df_bikes_paris.loc[0, 'longitude']

headers = {
    'Accept': 'application/json',
    'Authorization' : FOURSQUARE_API_KEY
}
url = 'https://api.foursquare.com/v3/places/search'
params = {
    'll' : f'{latitude},{longitude}',
    'radius' : 1000, 
    'categories' : '4d4b7105d754a06374d81259', # restaurants
    'limit' : 10
}

response = requests.get(url = url, headers = headers, params = params)

if response.status_code == 200:
    data = response.json()
else:
    print(f'{response.status_code}')

In [19]:
data['results'][0]

{'fsq_id': '4adcda11f964a520fb3521e3',
 'categories': [{'id': 13064,
   'name': 'Pizzeria',
   'short_name': 'Pizza',
   'plural_name': 'Pizzerias',
   'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/pizza_',
    'suffix': '.png'}},
  {'id': 13145,
   'name': 'Fast Food Restaurant',
   'short_name': 'Fast Food',
   'plural_name': 'Fast Food Restaurants',
   'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/fastfood_',
    'suffix': '.png'}},
  {'id': 13236,
   'name': 'Italian Restaurant',
   'short_name': 'Italian',
   'plural_name': 'Italian Restaurants',
   'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/italian_',
    'suffix': '.png'}}],
 'chains': [],
 'closed_bucket': 'VeryLikelyOpen',
 'distance': 626,
 'geocodes': {'drop_off': {'latitude': 48.884567, 'longitude': 2.258158},
  'main': {'latitude': 48.884662, 'longitude': 2.258079},
  'roof': {'latitude': 48.884662, 'longitude': 2.258079}},
 'link': '/v3/places/4adcda11f964a520fb3521e3',
 'location': {'address': '6 rue de Longchamp',
  'admin_region': 'Île-de-France',
  'country': 'FR',
  'formatted_address': '6 rue de Longchamp, 92200 Neuilly-sur-Seine',
  'locality': 'Neuilly-sur-Seine',
  'postcode': '92200',
  'region': 'Île-de-France'},
 'name': 'Livio',
 'related_places': {},
 'timezone': 'Europe/Paris'}

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [26]:
stations_data_foursquare = []

for i in range(len(df_bikes_paris)):
    latitude = df_bikes_paris.loc[i,'latitude']
    longitude = df_bikes_paris.loc[i, 'longitude']
    params = {
    'll' : f'{latitude},{longitude}',
    'radius' : 1000, 
    'categories' : '4d4b7105d754a06374d81259,4bf58dd8d48988d16d941735,4bf58dd8d48988d181941735', # restaurants, cafes and museums
    'limit' : 50 }
    response = requests.get(url = url, headers = headers, params = params)
    if response.status_code == 200:
        data = response.json()
    
        for place in data.get('results', []):
            place_info = {
                'station' : i,
                'name' : place.get('name'),
                'distance' : place.get('distance'),
                'address' : place.get('location',{}).get('address'),
                'category' : place.get('categories',[{}])[0].get('name')
            }
            stations_data_foursquare.append(place_info)
    else:
        print(f'{response.status_code}')

Put your parsed results into a DataFrame

In [45]:
df_foursquare = pd.DataFrame(stations_data_foursquare)
df_foursquare.to_csv('df_foursquare_csv.csv', index = False)
df_foursquare.head()

,station,name,distance,address,category
0,0,Livio,626,6 rue de Longchamp,Pizzeria
1,0,Maison Wok,494,4 rue des Poissonniers,Thai Restaurant
2,0,Les Pieds dans l'Eau,448,39 boulevard du Parc,French Restaurant
3,0,Big Fernand,506,142 avenue Charles de Gaulle,Burger Joint
4,0,Le Nouveau Paris,700,204 boulevard Bineau,Café

# Yelp

Send a request to Yelp with a small radius (1000m) for all the bike stations in your city of choice.

In [22]:
YELP_API_KEY = os.getenv('YELP_API_KEY')

latitude = df_bikes_paris.loc[0,'latitude']
longitude = df_bikes_paris.loc[0, 'longitude']

headers_yelp = {
    'Accept': 'application/json',
    'Authorization' : f'Bearer {YELP_API_KEY}'
}
url_yelp = 'https://api.yelp.com/v3/businesses/search'
params_yelp = {
    'latitude' : latitude,
    'longitude' : longitude,
    'radius' : 1000, 
    'categories' : 'italian,japanese,thai,french,mexican,cafes,museums',
    'limit' : 10
}

response_yelp = requests.get(url = url_yelp, headers = headers_yelp, params = params_yelp)

if response_yelp.status_code == 200:
    data_yelp = response_yelp.json()
else:
    print(f'{response_yelp.status_code}')

data_yelp['businesses'][0]

{'id': 'iSXAiRhlSfvXs4BczLSV1A',
 'alias': 'bustronome-paris',
 'name': 'Bustronome',
 'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/0WJcWgeG0XiFMCUR_okL5A/o.jpg',
 'is_closed': False,
 'url': 'https://www.yelp.com/biz/bustronome-paris?adjust_creative=SUsyvCn8xCP_o9yK60HAJg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=SUsyvCn8xCP_o9yK60HAJg',
 'review_count': 24,
 'categories': [{'alias': 'french', 'title': 'French'},
  {'alias': 'foodtours', 'title': 'Food Tours'}],
 'rating': 4.5,
 'coordinates': {'latitude': 48.87276, 'longitude': 2.294027},
 'transactions': [],
 'price': '€€€€',
 'location': {'address1': '2 avenue Kléber',
  'address2': '',
  'address3': '',
  'city': 'Paris',
  'zip_code': '75116',
  'country': 'FR',
  'state': '75',
  'display_address': ['2 avenue Kléber', '75116 Paris', 'France']},
 'phone': '+33954444555',
 'display_phone': '+33 9 54 44 45 55',
 'distance': 2800.6244226905637,
 'business_hours': [{'open': [{'is_overnight': False,
     'start': '1200',
     'end': '1400',
     'day': 0},
    {'is_overnight': False, 'start': '1930', 'end': '2330', 'day': 0},
    {'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 1},
    {'is_overnight': False, 'start': '1930', 'end': '2330', 'day': 1},
    {'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 2},
    {'is_overnight': False, 'start': '1930', 'end': '2330', 'day': 2},
    {'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 3},
    {'is_overnight': False, 'start': '1930', 'end': '2330', 'day': 3},
    {'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 4},
    {'is_overnight': False, 'start': '1930', 'end': '2330', 'day': 4},
    {'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 5},
    {'is_overnight': False, 'start': '1930', 'end': '2330', 'day': 5},
    {'is_overnight': False, 'start': '1200', 'end': '1400', 'day': 6},
    {'is_overnight': False, 'start': '1930', 'end': '2330', 'day': 6}],
   'hours_type': 'REGULAR',
   'is_open_now': True}],
 'attributes': {'business_temp_closed': None,
  'menu_url': 'http://www.bustronome.com/menu/',
  'open24_hours': None,
  'waitlist_reservation': None}}

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [33]:
stations_data_yelp = []

for i in range(len(df_bikes_paris)):
    latitude = df_bikes_paris.loc[i,'latitude']
    longitude = df_bikes_paris.loc[i, 'longitude']
    params_yelp = {
    'latitude' : latitude,
    'longitude' : longitude,
    'radius' : 1000, 
    'categories' : 'italian,japanese,thai,french,mexican,cafes,museums',
    'limit' : 50 }
    response_yelp = requests.get(url = url_yelp, headers = headers_yelp, params = params_yelp)
    if response_yelp.status_code == 200:
        data_yelp = response_yelp.json()
    
        for place in data_yelp.get('businesses', []):
            place_info = {
                'station' : i,
                'name' : place.get('name'),
                'distance' : place.get('distance'),
                'address' : place.get('location',{}).get('address1'),
                'rating' : place.get('rating')
            }
            stations_data_yelp.append(place_info)
    else:
        print(f'{response_yelp.status_code}')

Put your parsed results into a DataFrame

In [50]:
df_yelp = pd.DataFrame(stations_data_yelp)
df_yelp.to_csv('df_yelp_csv.csv', index = False)
df_yelp.head()

,station,name,distance,address,rating
0,0,Bustronome,2800.624423,2 avenue Kléber,4.5
1,0,La Boutarde,587.169143,4 rue Boutard,4.5
2,0,Sébillon,1526.963348,20 avenue Charles de Gaulle,4.0
3,0,Chartier Laure et Thomas,1884.634786,146 Rue Prés Wilson,3.9
4,0,Le Petit Poucet,950.317820,4 rond point Claude Monet,3.5

# Comparing Results

Which API provided you with more complete data? Provide an explanation.

In [49]:
print(df_foursquare.shape)
print(df_yelp.shape)
# more POI in the Yelp Database
print(df_foursquare.groupby('station').size().mean())
print(df_yelp.groupby('station').size().mean())
# Here again there is in average more POI per station in the Yelp Database
print(df_foursquare.describe())
print(df_yelp.describe())
# It seems that in general, the POIs are closer to the station in the Foursquare Dataframe, where in the Yelp Dataframe even with radius set to 100, a lot of the data is beyong that
print(df_foursquare.isnull().sum())
print(df_yelp.isnull().sum())
# The Foursquare DataFrame have a bit more missing values with 6 addresses missing, with only 2 in the df_yelp
# Yelp provides ratings of the different POIs, where Foursquare doesn't
# Even though Yelp doesn't provide the category so easily and clearly as Foursquare, Yelp still overall provides with more complexe data, so I will continue my analysis with the Yelp data

(9136, 5)
(9356, 5)
45.68
46.78
           station     distance
count  9136.000000  9136.000000
mean     99.389339   642.620293
std      57.075281   292.907266
min       0.000000     5.000000
25%      50.000000   453.000000
50%      99.000000   671.000000
75%     148.000000   850.000000
max     199.000000  6734.000000
           station      distance       rating
count  9356.000000   9356.000000  9356.000000
mean    100.324605   1043.495383     3.961415
std      57.508126    782.594737     0.926457
min       0.000000      1.847584     0.000000
25%      51.000000    522.522674     3.800000
50%     101.000000   1064.684340     4.200000
75%     150.000000   1429.316211     4.500000
max     199.000000  13539.532521     5.000000
station     0
name        0
distance    0
address     6
category    0
dtype: int64
station     0
name        0
distance    0
address     2
rating      0
dtype: int64

Get the top 10 restaurants according to their rating

In [42]:
df_yelp.sort_values(by = 'rating', ascending = False).head(10)

,station,name,distance,address,rating
7116,152,Issy l'Asie,1739.957651,7 rond-point Victor Hugo,5.0
802,17,O'Silver Sushi,1191.171372,3 bis rue gabriel péri,5.0
790,17,Le Médaillon,383.148530,85 Avenue République,5.0
791,17,Augusta Pizza,690.960856,114 rue de Chevilly,5.0
3785,81,Mini Festin,23.672855,7 rue Gros,5.0
796,17,Khankluay,1178.215786,125 rue Jean Jaurès,5.0
7503,160,Jacques,8.563508,129 avenue Victor Hugo,5.0
798,17,Sin Yong Houa,830.384638,33 ave du Général de Gaulle,5.0
7494,160,Sorella,258.259525,13 avenue Bugeaud,5.0
7441,159,Coupi Bar,1388.823859,48 avenue de la Porte d'Ivry,5.0